spring:
    application:
        name:
            bookstore
    h2:
        console.enabled: true
    datasource:
        url: jdbc:h2:mem:book
        driverClassName: org.h2.Driver
        username: user
        password: password
    jpa: 
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

management:
    endpoints:
        web:
            exposure:
                include:
                    mappings